from typing import List
from data import Piece, Position, Type

TYPE_INDEX = 1
PACKAGE_INDEX = 2
POS_X_INDEX = 3
POS_Y_INDEX = 4
ROTATION_INDEX = 5


class FileInterpreter:
    """
    Class that handles reading data from a .pos file, and transform this data
    into usable information for the storage and the slicer.
    """

    def readPositionFile(self, file_path:str) -> List[Piece]:
        """
        Reads a .pos file generated by Kicad, and stores important data in a list for the slicer.

        Parameters:
            file_path (str):
                the path of the .pos file
        
        Returns:
            List[Piece]
                the list of components thats needs to be placed on the PCB
        """
        try:
            file = open(file_path, "r")
        except FileNotFoundError:
            print(f"The file was not found : {file_path}")
            return None
        except PermissionError:
            print(f"Permission denied to access the file : {file_path}")
            return None

        pieces = []
        for line in file:
            #ignores comments
            if line[0] == "#":
                continue
            
            
            data = line.split() 

            #only add the usable components
            # TODO add more?
            if data[0][0] == "R":
                type = Type.RESISTOR
            elif data[0][0] == "D":
                type = Type.LED
            else :
                continue
            
            #TODO est ce que le z est managed ici?
            position = Position(x=float(data[POS_X_INDEX]), 
                                y=float(data[POS_Y_INDEX]),
                                z=0,
                                yaw=float(data[ROTATION_INDEX]))
            
            #TODO add a way to interpret value in kicad
            piece = Piece(position=position, package=data[PACKAGE_INDEX], type=type, value="")
            pieces.append(piece)
        
        file.close()
        return pieces