from typing import List
from data import Piece, Position, Type

TYPE_INDEX = 1
PACKAGE_INDEX = 2
POS_X_INDEX = 3
POS_Y_INDEX = 4
ROTATION_INDEX = 5


class FileInterpreter:
    """
    Class that handles reading data from a .pos file, and transform this data
    into usable information for the storage and the slicer.
    """

    def readPositionFile(self, file_path:str, reference_ref:str = "J4") -> List[Piece]:
        """
        Reads a .pos file generated by Kicad, and stores important data in a list for the slicer.

        Parameters:
            file_path (str):
                the path of the .pos file
            reference_ref (str):
                the reference designator used as the origin for the PCB position
        
        Returns:
            List[Piece]
                the list of components thats needs to be placed on the PCB
        """
        try:
            with open(file_path, "r") as file:
                pieces = []
                ref = Position(0, 0, 0, 0)
                referenceFound = False

                # Finds the reference component of the PCB
                for line in file:
                    # ignores comments
                    if not line or line[0] == "#":
                        continue

                    data = line.split()
                    if not data:
                        continue

                    if data[0] == reference_ref:
                        ref = Position(x=float(data[POS_X_INDEX]),
                                       y=float(data[POS_Y_INDEX]),
                                       z=0,
                                       yaw=float(data[ROTATION_INDEX]))
                        referenceFound = True
                        break

                if not referenceFound:
                    raise ReferenceNotFoundError(
                        f"Reference '{reference_ref}' was not found in the position file"
                    )

                file.seek(0)
                for line in file:
                    # ignores comments
                    if not line or line[0] == "#":
                        continue

                    data = line.split()
                    if not data:
                        continue

                    # only add the usable components
                    # TODO add more?
                    if data[0][0] == "R":
                        type = Type.RESISTOR
                    elif data[0][0] == "D":
                        type = Type.LED
                    else:
                        continue

                    position = Position(x=float(data[POS_X_INDEX]),
                                        y=float(data[POS_Y_INDEX]),
                                        z=0,
                                        yaw=float(data[ROTATION_INDEX]))

                    position = position - ref

                    # TODO add a way to interpret value in kicad
                    piece = Piece(position=position, package=data[PACKAGE_INDEX], type=type, value="")
                    pieces.append(piece)

                return pieces
        except FileNotFoundError:
            print(f"The file was not found : {file_path}")
            return None
        except PermissionError:
            print(f"Permission denied to access the file : {file_path}")
            return None


class ReferenceNotFoundError(Exception):
    """Raised when the requested reference designator is not present in the .pos file."""